title: Ankur Padia
#logo: /assets/img/logo3.png
description: Director, Data Science and Machine Learning, at Liberty Mutual Insurance 
show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
#circular_avatar:  "true"
